### PR TITLE
 Issue #56

### PR DESCRIPTION
**Pull request by gainskills**
#56
1. no file type on MAC OS
2. avoiding UI frozen
3. format the file with black

### CODE REVIEW

**Comment by brentvollebregt** [comment]
I am more of a fan for the 
```python
if (file_type is None) or (platform.system() == "Darwin"):
```
over my
```python
if platform.system() == 'Darwin':
```
however this pull request is for #56, does it need all the formatting fixes?

I was going to fix a bit of the formatting another day but in my opinion it isn't that bad currently and I rather `'` over `"` (it's a crime, I know). This pull request is 90% formatting; could we focus on the issue?

**Comment by gainskills** [comment]
Hi,
1. `if (file_type is None) or (platform.system() == "Darwin")`
extends your condition
2. `root.update()` is for UI frozen, refer to https://stackoverflow.com/questions/51662441/python-tkinter-askopenfilename-not-responding 
Thanks,

**Comment by brentvollebregt** [comment]
Oh right, I see what `root.update()` is used for now. I had said that I liked `if (file_type is None) or (platform.system() == "Darwin")` over the change that is currently in the master branch.

If you undo the formatting and keep the actual logic changes here, I will be happy to merge. I would rather separate the logic and formatting in the scope of commits so we can actually see what is being changed here.

In terms of formatting fixes for later, I can run it though Black also but if the Python is going to be formatted, so should the JavaScript, CSS and HTML. I feel that before formatting occurs, I would rather spend some time looking at the actual logic and seeing if some things could be made simpler and maybe separated.

**Comment by brentvollebregt** [comment]
Awesome, thanks for that. I squashed the commits to remove the formatting changes and keep the logic improvements. Thanks heaps for this!

**Pull request merged**
